Repository boucadair/attachment-circuit-model, pull requests merged in 2023-03, with the labels that each got.

#37 Bearer Definition
  yang/full-trees/bearers-stree.txt
  yang/ietf-ac-svc.yang
  yang/ietf-bearer-svc.yang
  yang/ietf-vpn-common@2022-02-11.yang
Labels: YANG

#55 Adding some words to improve readability
  draft-boro-opsawg-teas-attachment-circuit.md
Labels: AC-SVC

#57 Review of Section 3
  draft-boro-opsawg-teas-attachment-circuit.md
Labels: AC-SVC

#64 review up to example A5 (included)
  draft-boro-opsawg-teas-attachment-circuit.md
Labels: AC-SVC

#61 add ac-refs to the bearer-svc
  yang/ietf-bearer-svc.yang
Labels: bearer-svc

#66 Restructure the profile examples
  draft-boro-opsawg-teas-attachment-circuit.md
Labels: Editorial, AC-SVC
